### ISSUE TITLE
w5-Visualization-project[YasminMoreno]

### ISSUE THREAD

**Issue by YasminMoreno** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#11]
https://github.com/YasminMoreno/-w5-Visualization-project.git

**Comment by Gobuub** [comment]
No he podido ver el dashboard Yasmine, porque supongo que lo tendrás en Tableau Desktop y no en el public, pero se compensa con un readme detallado y con las conclusiones lo que me ayuda ha entender el trabajo que realizaste.
