### ISSUE TITLE
W5-Visualization-project Public - {Carlos Basco}

### ISSUE THREAD

**Issue by Carlosbasco93** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#14]
https://github.com/Carlosbasco93/W5-VisualizationProyect-PBI

**Comment by Gobuub** [comment]
Está muy currado, sin conocer la historia es dificil poder sacarle chicha al dashboard, quiero decir que los dashboard se entienden mejor cuando el que lo ha hecho te explica el porqué de cada gráfico.
