### ISSUE TITLE
w5-Visualization-project [José Rojas]

### ISSUE THREAD

**Issue by joserojas95** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#15]
https://github.com/joserojas95/p.final

**Comment by Gobuub** [comment]
El dashboard tiene mucho curro, pero el repo es muy pobre Jose, que quiero decir, no tiene readme, los archivos no están en carpetas, sin el readme no se exactamente la finalidad del proyecto y tengo que tratar de deducirlo por el dashboard, los títulos de los gráficos son muy largos, lo que dificulta su visualización, que quiero decir con todo esto, el proyecto está bien, pero requiere un poco de pulido ;).
