### ISSUE TITLE
w5-Visualization-project_Berta

### ISSUE THREAD

**Issue by Vert-ix** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#16]
[w5-Visualization-project_Berta](https://github.com/Vert-ix/w5-Visualization-project_Berta)

**Comment by Gobuub** [comment]
Buen trabajo Berta, el repo un poco pobre, que quiero decir con esto, no hay readme, están los archivos todos en el mismo sitio sin jerarquía de carpetas, etc. Luego en cuanto al dashboard se podrían pulir algunas cosillas como tema de elección de colores, títulos, etc, pero en líneas generales está muy bien :).
