### ISSUE TITLE
w5-Visualization-project Public-solution[Lucia Correa]

### ISSUE THREAD

**Issue by AtomLu** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#4]
https://github.com/AtomLu/Tableau-project.git
[netflix_titles.csv](https://github.com/Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project/files/9543271/netflix_titles.csv)

**Comment by Gobuub** [comment]
Perfect Lucia, buen trabajo, los colores bien elegidos, te falto ponerle el fondo negro ;).
