### ISSUE TITLE
w5-Visualization {Mar.Sanchez.de.Salas}

### ISSUE THREAD

**Issue by Mar26sds** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#5]
https://github.com/Mar26sds/proyecto_mamiferos_espa-a/blob/main/README.md

**Comment by Gobuub** [comment]
No me has subido el dashboard o el enlace a tableau public Mar, no he podido ver nada.

**Comment by Gobuub** [comment]
Sorry, es que el enlace me había llevado directamente al readme, no al repo XDD, pero bueno el dashboard no he podido verlo al estar en tableau desktop, seguro que está guay ;).
