### ISSUE TITLE
w5 - Visualization Project (Jaime Leoz)

### ISSUE THREAD

**Issue by JaimeLeoz** [Ironhack-Data-Madrid-Agosto-2022/w5-Visualization-project#7]
https://github.com/JaimeLeoz/w5-Visualization-project

**Comment by Gobuub** [comment]
Muy buen trabajo Jaime, mucho curro detrás de él, estoy deseando ver el resultado final a ver si funciona el ML, y podemos irnos de vacaciones de forma baratita :P.
